# Generated by Django 6.0.7 on 2026-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('highlighted_text', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('feature1_title', models.CharField(max_length=100)),
                ('feature1_description', models.TextField()),
                ('feature2_title', models.CharField(max_length=100)),
                ('feature2_description', models.TextField()),
                ('feature3_title', models.CharField(max_length=100)),
                ('feature3_description', models.TextField()),
                ('feature4_title', models.CharField(max_length=100)),
                ('feature4_description', models.TextField()),
                ('customers', models.CharField(max_length=20)),
                ('menu_items', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
                ('primary_button', models.CharField(max_length=100)),
                ('primary_link', models.CharField(max_length=200)),
                ('secondary_button', models.CharField(max_length=100)),
                ('secondary_link', models.CharField(max_length=200)),
                ('signature_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
