# Generated by Django 6.0.7 on 2026-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('highlighted_text', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('desktop_image', models.ImageField(upload_to='hero/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('primary_button_text', models.CharField(max_length=100)),
                ('primary_button_link', models.CharField(default='#menu', max_length=200)),
                ('secondary_button_text', models.CharField(max_length=100)),
                ('secondary_button_link', models.CharField(default='#events', max_length=200)),
                ('stat1_value', models.CharField(max_length=20)),
                ('stat1_label', models.CharField(max_length=80)),
                ('stat2_value', models.CharField(max_length=20)),
                ('stat2_label', models.CharField(max_length=80)),
                ('stat3_value', models.CharField(max_length=20)),
                ('stat3_label', models.CharField(max_length=80)),
                ('feature1_text', models.CharField(max_length=100)),
                ('feature2_text', models.CharField(max_length=100)),
                ('feature3_text', models.CharField(max_length=100)),
                ('feature4_text', models.CharField(max_length=100)),
                ('feature5_text', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
