# Generated by Django 6.0.7 on 2026-08-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='website/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='website/favicon/')),
                ('footer_description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('google_maps_url', models.URLField()),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('weekday_label', models.CharField(max_length=100)),
                ('weekday_hours', models.CharField(max_length=100)),
                ('weekend_label', models.CharField(max_length=100)),
                ('weekend_hours', models.CharField(max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(max_length=250)),
                ('made_with_text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
