# Generated by Django 6.0.7 on 2026-08-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_websitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='website/logo/'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
