# Generated by Django 6.0.7 on 2026-08-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hidden_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
