# Generated by Django 6.0.7 on 2026-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_booking_guests_gt_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
