# Generated by Django 6.0.7 on 2026-08-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hidden_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
