# Generated by Django 6.0.7 on 2026-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_total_gte_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
