# Generated by Django 6.0.7 on 2026-08-12 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_total_gte_0_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Processed', 'Processed'), ('Failed', 'Failed')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['refund_status', '-created_at'], name='payment_refund_status_idx'),
        ),
    ]
