# Generated by Django 6.0.7 on 2026-08-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_booking_confirmation_email_sent_and_more'),
        ('payments', '0002_payment_provider_refund_id_payment_refund_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Razorpay', 'Razorpay')], default='Razorpay', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Created', max_length=20)),
                ('provider_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_signature', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider_refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('refund_status', models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Processed', 'Processed'), ('Failed', 'Failed')], default='None', max_length=20)),
                ('refund_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookpay_user_status_idx'), models.Index(fields=['status', '-created_at'], name='bookpay_status_created_idx'), models.Index(fields=['refund_status', '-created_at'], name='bookpay_refund_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='bookpay_amount_non_negative')],
            },
        ),
    ]
